"""Strategy profile constants used by the live planner.

This module contains policy preferences only. It does not execute game actions,
write ledgers, or know about live strict gateway state.
"""

TECH_PRIORITY = [
    "TECH_POTTERY",
    "TECH_ANIMAL_HUSBANDRY",
    "TECH_MINING",
    "TECH_WRITING",
    "TECH_ARCHERY",
    "TECH_IRRIGATION",
    "TECH_BRONZE_WORKING",
    "TECH_MASONRY",
    "TECH_THE_WHEEL",
    "TECH_CURRENCY",
    "TECH_HORSEBACK_RIDING",
    "TECH_CONSTRUCTION",
    "TECH_ENGINEERING",
    "TECH_APPRENTICESHIP",
]

CIVIC_PRIORITY = [
    "CIVIC_CODE_OF_LAWS",
    "CIVIC_CRAFTSMANSHIP",
    "CIVIC_FOREIGN_TRADE",
    "CIVIC_EARLY_EMPIRE",
    "CIVIC_STATE_WORKFORCE",
    "CIVIC_POLITICAL_PHILOSOPHY",
    "CIVIC_MILITARY_TRADITION",
    "CIVIC_GAMES_RECREATION",
    "CIVIC_DRAMA_POETRY",
]

POLICY_PRIORITY = [
    "POLICY_URBAN_PLANNING",
    "POLICY_DISCIPLINE",
    "POLICY_GOD_KING",
    "POLICY_AGOGE",
    "POLICY_CARAVANSARIES",
    "POLICY_COLONIZATION",
]

DEDICATION_PRIORITY = [
    "COMMEMORATION_SCIENTIFIC",
    "COMMEMORATION_FREE_INQUIRY",
    "COMMEMORATION_MONUMENTALITY",
    "COMMEMORATION_EXODUS",
]

PRODUCTION_PRIORITY_EXPAND = [
    "UNIT_SETTLER",
    "UNIT_BUILDER",
    "UNIT_SLINGER",
    "BUILDING_MONUMENT",
    "UNIT_WARRIOR",
    "BUILDING_GRANARY",
]

PRODUCTION_PRIORITY_STABILIZE = [
    "UNIT_BUILDER",
    "UNIT_SLINGER",
    "BUILDING_MONUMENT",
    "BUILDING_GRANARY",
    "UNIT_SETTLER",
    "UNIT_WARRIOR",
]
